BibliotecaWeb/BibliotecaWeb/Models/ViewModels/LibroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BibliotecaWeb.Models.ViewModels
{
    public class LibroViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        [MaxLength(250, ErrorMessage = "El campo debe tener como maximo {0}")]
        [MinLength(1, ErrorMessage = "El campo debe tener como minimo {0}")]
        [DataType(DataType.Text)]
        public string Nombre { get; set; }

        [Required]
        [Display(Name ="Portada")] 
        [DataType(DataType.Upload)]
        public string Portada { get; set; }

        [Required]
        [Display(Name = "Fecha de adquisicion")]
        [MaxLength(250, ErrorMessage = "El campo debe tener como maximo {0}")]
        [MinLength(1, ErrorMessage = "El campo debe tener como minimo {0}")]
        public string FechaAdquirido{ get; set; }

 


        [Required]
        [Display(Name = "Observacion")]
        [MaxLength(250, ErrorMessage = "El campo debe tener como maximo {0}")]
        [MinLength(1, ErrorMessage = "El campo debe tener como minimo {0}")]
        public string Observacion { get; set; } 
    }
}

BibliotecaWeb/BibliotecaWeb/Models/libro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libro()
        {
            this.genero_libro = new HashSet<genero_libro>();
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int id_libro { get; set; }
        public string nombre { get; set; }
        public string portada { get; set; }
        public System.DateTime fecha_adquirido { get; set; }
        public string observacion { get; set; }
        public int fk_estado_libro { get; set; }
        public int fk_editorial { get; set; }
        public int fk_autor { get; set; }
    
        public virtual autor autor { get; set; }
        public virtual editorial editorial { get; set; }
        public virtual estado_libro estado_libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genero_libro> genero_libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}

BibliotecaWeb/BibliotecaWeb/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaWeb.Models;
using BibliotecaWeb.Models.ViewModels;
using BibliotecaWeb.Models.TableViewModels;
using System.IO;

namespace BibliotecaWeb.Controllers
{
    public class LibrosController : Controller
    {
     
        [HttpGet]
        public ActionResult Consult() {
            int tipoS = ((int)Session["userActivoTipo"]);
            List<LibroTableViewModel> lista = null; 
            using (var db  = new bibliotecaEntities1()) {
                lista = (from t1 in db.libro
                         join t2 in db.autor on t1.fk_autor equals t2.id_autor
                         join t3 in db.editorial on t1.fk_editorial equals t3.id_editorial
                         orderby t1.nombre descending
                         select new LibroTableViewModel
                         {
                             Fk_estado_libro = t1.fk_estado_libro,
                             Id_libro = t1.id_libro,
                             Nombre = t1.nombre,
                             Portada = t1.portada,
                             Observacion = t1.observacion,
                             Autor = t2.nombre,
                             Editorial = t3.nombre,
                             generosLiterarios = (from t4 in db.generoLiterario
                                                  join t5 in db.genero_libro on t4.id_genero equals t5.fk_genero
                                                  where t5.fk_libro == t1.id_libro
                                                  orderby t4.nombre descending
                                                  select t4.nombre ).ToList()

                         }).ToList(); 
            } 
           return View(lista);
        }

        [HttpGet]
        public ActionResult Add() {


            List<EditorialTableViewModel> lEditorial = null;
            List<AutorTableViewModel> lAutor = null;
            List<GeneroLiterarioTableViewModel> lGenero = null;

            using (var db = new bibliotecaEntities1()) {
                lEditorial = (from t1 in db.editorial
                              orderby t1.nombre descending
                              select new EditorialTableViewModel
                              {
                                  Id_editorial = t1.id_editorial,
                                  Nombre = t1.nombre
                              }).ToList();

                lGenero = (from t1 in db.generoLiterario
                           orderby t1.nombre descending
                           select new GeneroLiterarioTableViewModel
                           {
                               Id_Genero = t1.id_genero,
                               Nombre = t1.nombre
                           }).ToList();

                lAutor = (from t1 in db.autor
                          orderby t1.nombre descending
                          select new AutorTableViewModel
                          {
                               Id_autor  = t1.id_autor,
                               Nombre= t1.nombre 
                          }).ToList();
            }

            ViewBag.vGenero = lGenero;
            ViewBag.vEditorial = lEditorial;
            ViewBag.vAutor = lAutor;
                return View();
        }

        [HttpPost]
        public ActionResult Add(LibroViewModel model,HttpPostedFileBase portada,int[] _generoLiterario,string _Autor,string _Editorial ){
            if (!ModelState.IsValid) {
                this.Add();
            }

 
            if (portada != null && portada.ContentLength>0)
            {
                try
                {

                    string nombreFinal = model.Nombre + "-" + DateTime.Now.ToString("MM-dd-yyyy") + Path.GetExtension(portada.FileName);
                    string rutaB= Path.Combine(Server.MapPath("~/Img/Portadas"),nombreFinal );
                    portada.SaveAs(rutaB); 
                    using (var db = new bibliotecaEntities1())
                    {
                        libro oLibro = new libro
                        {
                            nombre = model.Nombre,
                            portada = nombreFinal,
                            fecha_adquirido = DateTime.Parse(model.FechaAdquirido),
                            observacion = model.Observacion,
                            fk_estado_libro =1,
                            fk_editorial =  int.Parse(_Editorial) ,
                            fk_autor = int.Parse(_Autor)
                        };

                        db.libro.Add(oLibro);
                        db.SaveChanges();

                        for (int i = 0; i < _generoLiterario.Length; i++) {
                            genero_libro oGenero = new genero_libro
                            {
                                fk_libro = oLibro.id_libro,
                                fk_genero = _generoLiterario[i]
                            };
                            db.genero_libro.Add(oGenero);
                            db.SaveChanges();
                        }
                    }
                }
                catch (Exception)
                {
                    ViewBag.Message = "Error";
                }
            }

 

            return Redirect(Url.Content("~/Libros/Consult"));
        }
    }
}

BibliotecaWeb/BibliotecaWeb/Views/Libros/Add.cshtml
@model BibliotecaWeb.Models.ViewModels.LibroViewModel
@{
    ViewBag.Title = "Agregar libro";
    Layout = "~/Views/Shared/LayoutAdministrador.cshtml";

    var vAutor = ViewBag.vEditorial as IEnumerable<SelectList>; //new SelectList(.Value, ViewBag.vAutor.Text)
}

<div class="row">
    <div class="col-md-10">
        @using (Html.BeginForm("Add", "Libros", FormMethod.Post, new { role = "form", enctype="multipart/form-data" }))
        {
            <h3>Agregar libro</h3>
            @Html.AntiForgeryToken();
            <div class="col-md-6">
                @Html.LabelFor(l => l.Nombre)
                @Html.TextBoxFor(l => l.Nombre, new { @class = "form-control text-danger" })
                @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
            </div>
            <div class="col-md-6">
                @Html.LabelFor(l => l.FechaAdquirido)
                @Html.TextBoxFor(l => l.FechaAdquirido, new { @class = "form-control text-danger datePicker" })
                @Html.ValidationMessage("Fecha adquirido", new { @class = "text-danger" })
            </div>


            <div class="col-md-6">
                <label>Autor</label>
                <select class="form-control" name="_Autor">
                    <option value="A0">Seleccione</option>
                    @foreach (var iAutor in ViewBag.vAutor)
                    {
                        <option value="@iAutor.Id_autor">@iAutor.Nombre</option>
                    }
                </select>

                @Html.ValidationMessage("Autor", new { @class = "text-danger" })
            </div>

            <div class="col-md-6"> 
                <label>Editorial</label>
                <select class="form-control" name="_Editorial">
                    <option value="A0">Seleccione</option>
                    @foreach (var item in ViewBag.vEditorial)
                    {
                        <option value="@item.Id_editorial">@item.Nombre</option>
                    }
                </select>

                @Html.ValidationMessage("Autor", new { @class = "text-danger" })
            </div>

            <div class="col-md-6">

                <label>Generos literarios</label>
                <br />
                @foreach (var lGenero in ViewBag.vGenero)
                {
                <label>
                    <input type="checkbox" value="@lGenero.Id_Genero" name="_generoLiterario">
                    @lGenero.Nombre
                </label>        
                }




            </div>

            <div class="col-md-6">
                @Html.LabelFor(l => l.Portada)
                <input class="text-danger" type="file" accept="image/png, image/jpeg, image/jpg" id="fileInput" name="portada"/> 
            </div>

            <div class="col-md-10">
                @Html.LabelFor(l => l.Observacion)
                @Html.TextAreaFor(l => l.Observacion, new { @class = "form-control text-danger" })
                @Html.ValidationMessage("Observacion", new { @class = "text-danger" })
            </div>

            <div class="col-md-12">
                <br />
                <button class="btn btn-success" type="submit"> Agregar</button>
            </div>
        }
    </div>
</div>

 

@section scripts{
    <script>

        $(document).ready(function () {
            console.log(":v");
            var nLista = "";
            $(".datePicker").datepicker({
                changeYear: true,
                changeMonth: true,
                dateFormat: ("yy-mm-dd")

            });

            $("#fileInput").change(function () {
                console.log($(this).val());
                nLista = $(this).val().split(".");
                nPuntos = nLista.length-1; 
                console.log(nLista[nPuntos]);
                if ((nLista[nPuntos] != "jpg") && (nLista[nPuntos] != "png") && (nLista[nPuntos] != "jpeg")) {
                    $(this).val("");
                    $(this).removeClass("text-success").addClass("text-danger");
                } else {
                    $(this).removeClass("text-danger").addClass("text-success");
                }

            });
        });
    </script>

    }

BibliotecaWeb/BibliotecaWeb/Views/Libros/Consult.cshtml
@model  List<BibliotecaWeb.Models.TableViewModels.LibroTableViewModel>
@{
    ViewBag.Title = "Consultar libros";
    int tipoS = ((int)Session["userActivoTipo"]);

    if (tipoS == 2)
    {
        Layout = "~/Views/Shared/LayoutLector.cshtml";
    }
    else if (tipoS == 1)
    {
        Layout = "~/Views/Shared/LayoutAdministrador.cshtml";
    }

}


<div class="row">
    <h3>Estante de libros</h3>
    <div class="row">

        @foreach (var oLibro in Model)
        {
            if (((tipoS == 2) && (oLibro.Fk_estado_libro != 4)) || (tipoS == 1))
            {
                <div class="card col-md-2" style="width: 25rem;">

                    @{ string portadaI = "~/Img/Portadas/sinPortada.jpg";}
                    @if (oLibro.Portada != "")
                    {
                        portadaI = "~/Img/Portadas/" + oLibro.Portada;

                    }

                    <img src="@Url.Content(portadaI)" class="card-img-top" style="margin-left: 18%; width:50%">
                    <div class="card-body">
                        <h5 class="card-title">@oLibro.Nombre</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <h5><strong>Autor:</strong></h5>
                                <p>
                                    @oLibro.Autor
                                </p>
                            </li>
                            <li class="list-group-item">
                                <h5><strong>Descripcion:</strong></h5>
                                <p>
                                    @oLibro.Observacion
                                </p>
                            </li>
                            <li class="list-group-item">
                                <h5><strong>Generos literarios:</strong></h5>
                                <p>
                                    @{ var lGenero = ""; }

                                    @for (int i = 0; i < oLibro.generosLiterarios.Count; i++)
                                    {
                                        if (i == 0)
                                        {
                                            lGenero += oLibro.generosLiterarios[i];
                                        }
                                        else
                                        {
                                            lGenero += ", " + oLibro.generosLiterarios[i];
                                        }
                                    }
                                    @lGenero
                                </p>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        @if (tipoS == 1)
                        {
                            <button id="@oLibro.Id_libro" class="btn btn-info btnModificar">Modificar</button>
                            <button id="@oLibro.Id_libro" class="btn btn-danger btnEliminar">Eliminar</button>
                        }
                    </div>
                </div>
            }
        }
    </div>

    <div class="col-md-12">
        <button class="btn btn-success" id="btnAgregar">Agregar</button>

    </div>

</div>


<div class="modal fade" id="basicModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Eliminar libro</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8">
                        <label for="Enombre">Nombre</label>
                        <input id="Enombre" class="form-control" />
                    </div>
                    <div class="col-md-8">
                        <label for="Etelefono">Telefono</label>
                        <input id="Etelefono" class="form-control" />
                    </div>
                    <div class="col-md-8">
                        <label for="Ecorreo">Correo</label>
                        <textarea id="Ecorreo" class="form-control"> </textarea>
                    </div>
                    <div class="col-md-8">
                        <label for="Edirrecion">Dirrecion</label>
                        <textarea id="Edirrecion" class="form-control"> </textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-danger" id="btnEliminar">Eliminar editorial</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {
            console.log(":v");
            $("#btnAgregar").click(function () {
                document.location = '';
                document.location = '@Url.Content("~/Libros/add")';
            });
        });
    </script>
}