BibliotecaWeb/BibliotecaWeb/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaWeb.Models;
using BibliotecaWeb.Models.ViewModels;

namespace BibliotecaWeb.Controllers
{
    public class AccessController : Controller
    {
        [HttpGet]
        public ActionResult Ingresar() {
            return View();
        }

        [HttpPost]
        public ActionResult Ingresar(UserViewModel model) {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new bibliotecaEntities1())
            {
                var list = from t1 in db.usuario
                           where t1.correo == model.Correo && t1.contrasena == model.Contrasena && t1.fk_estadoUsuario == 1
                           select t1;
                if (list.Count() == 1)
                {

                    Session["userActivo"] = list.First();
                    foreach (var dataUsuario in list)
                    {
                        
                        Session["userActivoTipo"] = dataUsuario.fk_tipoUsuario;
                        Session["userActivoNombre"] = dataUsuario.nombre;
                        if (dataUsuario.fk_tipoUsuario == 2)
                        {
                            return Redirect(Url.Content("~/Lector/Index"));
                        }
                        else if (dataUsuario.fk_tipoUsuario == 1)
                        {
                            return Redirect(Url.Content("~/Administrador/Index"));
                        }
                    }
                } 
                else
                {
                    model.estado = true;
                }
            }

            return View(model);

        }

        public ActionResult Logout()
        {
            Session["userActivo"] = null;
            return Redirect(Url.Content("~/Access/Ingresar"));
        }

    }
}

BibliotecaWeb/BibliotecaWeb/Controllers/GeneroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaWeb.Models;
using BibliotecaWeb.Models.ViewModels;
using BibliotecaWeb.Models.TableViewModels; 

namespace BibliotecaWeb.Controllers
{
    public class GeneroController : Controller
    {
        [HttpGet]
        public ActionResult ConsultGenero() {
            List<GeneroLiterarioTableViewModel> lista = null;
            using (var db = new bibliotecaEntities1()) {
                lista = (from t1 in db.generoLiterario
                         orderby t1.nombre descending
                         select new GeneroLiterarioTableViewModel
                         {
                             Id_Genero = t1.id_genero,
                             Nombre = t1.nombre,
                             Descripcion = t1.descripcion
                         }).ToList();
            }
            return View(lista);
        }

        [HttpGet]
        public ActionResult Add() {
            return View();
        }

        [HttpPost]
        public ActionResult Add(GeneroLiterarioViewModel model) { 
            if (! ModelState.IsValid) {
                return View(model);
            }

            using (var db = new bibliotecaEntities1()) {

                generoLiterario oGenero = new generoLiterario
                {
                    nombre = model.Nombre,
                    descripcion = model.Descripcion
                }; 
                db.generoLiterario.Add(oGenero);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Genero/ConsultGenero"));
        }

        public ActionResult Update(int NGenero, string nombre, string descripcion) {
             using (var db = new bibliotecaEntities1())
            {
                generoLiterario oGenero = db.generoLiterario.Find(NGenero);
                oGenero.nombre = nombre;
                oGenero.descripcion = descripcion;
                db.Entry(oGenero).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
                return Content("1");
        }
        public ActionResult Delete(int NGenero) { 
            using (var db = new bibliotecaEntities1()) {
                generoLiterario oGenero = db.generoLiterario.Find(NGenero); 
                db.Entry(oGenero).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
            }

                return Content("1");
        }

    }
}

BibliotecaWeb/BibliotecaWeb/Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BibliotecaWeb.Controllers
{
    public class PrestamoController : Controller
    {
        // GET: Prestamo
        public ActionResult Index()
        {
            return View();
        }
    }
}

BibliotecaWeb/BibliotecaWeb/Views/Shared/LayoutAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Administrador</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca", "Index", "Acess", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Libros", "Consult", "Libros")</li>
                    <li>@Html.ActionLink("Editoriales", "Consult", "Editorial")</li>
                    <li>@Html.ActionLink("Generos literarios", "ConsultGenero", "Genero")</li>
                    <li>@Html.ActionLink("Autor", "Autor", "Autor")</li>
                    <li>@Html.ActionLink("Prestamos", "Index", "Prestamo")</li>
                    <li>@Html.ActionLink("Cerrar session", "Logout", "Access")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Biblioteca</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BibliotecaWeb/BibliotecaWeb/Views/Shared/LayoutLector.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Lector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca", "Index", "Acess", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Libros", "Index", "Libros")</li>
                    <li>@Html.ActionLink("Prestamos", "Index", "Prestamos")</li>
                    <li>@Html.ActionLink("Cerrar session", "Logout", "Access")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Biblioteca</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BibliotecaWeb/BibliotecaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca", "Index", "Acess", new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Biblioteca </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>