BibliotecaWeb/BibliotecaWeb/Models/ViewModels/EditorialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace BibliotecaWeb.Models.ViewModels
{
    public class EditorialViewModel
    {
        [Required]
        [Display(Name ="Nombre")] 
        [MaxLength(250,ErrorMessage ="EL campo no debe ser mayor a {0}")]
        [MinLength(1,ErrorMessage ="El campo no debe ser menor de {0}")]
       public string Nombre { get; set; }

        [Required]
        [Display(Name = "Telefono")]
        [MaxLength(250, ErrorMessage = "EL campo no debe ser mayor a {0}")]
        [MinLength(1, ErrorMessage = "El campo no debe ser menor de {0}")]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "Correo")]
        [MaxLength(250, ErrorMessage = "EL campo no debe ser mayor a {0}")]
        [MinLength(1, ErrorMessage = "El campo no debe ser menor de {0}")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }
        [Required]
        [Display(Name = "Dirrecion")]
        [MaxLength(250, ErrorMessage = "EL campo no debe ser mayor a {0}")]
        [MinLength(1, ErrorMessage = "El campo no debe ser menor de {0}")]
        public string Dirrecion { get; set; }
    }
}

BibliotecaWeb/BibliotecaWeb/Models/editorial.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class editorial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public editorial()
        {
            this.libro = new HashSet<libro>();
        }
    
        public int id_editorial { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string dirrecion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libro { get; set; }
    }
}

BibliotecaWeb/BibliotecaWeb/Controllers/EditorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaWeb.Models;
using BibliotecaWeb.Models.ViewModels;
using BibliotecaWeb.Models.TableViewModels;

namespace BibliotecaWeb.Controllers
{
    public class EditorialController : Controller
    {

        [HttpGet]
        public ActionResult Consult() {
            List<EditorialTableViewModel> lista = null; 
            using (var bd = new bibliotecaEntities1()) { 
                lista = (from t1 in bd.editorial
                          orderby t1.nombre descending
                          select new EditorialTableViewModel
                          {
                              Id_editorial = t1.id_editorial,
                              Nombre = t1.nombre,
                              Telefono = t1.telefono,
                              Correo = t1.correo, 
                              Dirrecion  =t1.dirrecion 
                          }).ToList(); 
            } 
          return View(lista);
        }

        [HttpGet]
        public ActionResult Add() {
            return View();
        }
        [HttpPost]
        public ActionResult Add(EditorialViewModel model) {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var bd = new bibliotecaEntities1())
            { 
                editorial oEditorial = new editorial
                { 
                    nombre = model.Nombre,
                    telefono = model.Telefono,
                    correo = model.Correo,
                    dirrecion = model.Correo
                };
                bd.editorial.Add(oEditorial);
                bd.SaveChanges();
            } 
                return Redirect(Url.Content("~/Editorial/Consult"));
        }

        [HttpPost]
        public ActionResult Edit(int nEditorial,string nombre,string telefono,string correo,string dirrecion) {
            using (var db = new bibliotecaEntities1()) {
                var oEditorial = db.editorial.Find(nEditorial);
                oEditorial.nombre = nombre;
                oEditorial.telefono = telefono;
                oEditorial.correo = correo;
                oEditorial.dirrecion = dirrecion;
                db.Entry(oEditorial).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            } 
                return Content("1");
        }

        [HttpDelete]
        public ActionResult Delete(int nEditorial) { 
            using (var db = new bibliotecaEntities1())
            {
               var editorial =  db.editorial.Find(nEditorial);
                db.Entry(editorial).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
            } 
            return Content("1");
        }

        public ActionResult DaPrueba(JsonResult  data) { 
            Console.WriteLine(data); 
            return View(data);
        }
    }
}

BibliotecaWeb/BibliotecaWeb/Views/Editorial/Add.cshtml
@model BibliotecaWeb.Models.ViewModels.EditorialViewModel
@{
    ViewBag.Title = "Agregar";
    int tipoS = ((int)Session["userActivoTipo"]);

    if (tipoS == 2)
    {
        Layout = "~/Views/Shared/LayoutLector.cshtml";
    }
    else if (tipoS == 1)
    {
        Layout = "~/Views/Shared/LayoutAdministrador.cshtml";
    }
}
<div class="row">
    <div class="col-md-10" id="divAgregar">

        @using (Html.BeginForm("Add", "Editorial", FormMethod.Post, new { role = "form" }))
        {

            @Html.AntiForgeryToken();
            <h3>Agregar editorial</h3>
            <div class="col-md-12">
                @Html.LabelFor(l => l.Nombre)
                @Html.TextBoxFor(l => l.Nombre, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
            </div>

            <div class="col-md-12">
                @Html.LabelFor(l => l.Telefono)
                @Html.TextBoxFor(l => l.Telefono, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Telefono", new { @class = "text-danger" })
            </div>

            <div class="col-md-12">
                @Html.LabelFor(l => l.Correo)
                @Html.TextBoxFor(l => l.Correo, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Correo", new { @class = "text-danger" })
            </div>

            <div class="col-md-12">
                @Html.LabelFor(l => l.Dirrecion)
                @Html.TextBoxFor(l => l.Dirrecion, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Dirrecion", new { @class = "text-danger" })
            </div> 
            <div class="col-md-12">
                <br />
                <button class="btn btn-success " type="submit">Agregar</button>
            </div>
        }

    </div> 
</div>

BibliotecaWeb/BibliotecaWeb/Views/Editorial/Consult.cshtml
@model List<BibliotecaWeb.Models.TableViewModels.EditorialTableViewModel>
@{
    ViewBag.Title = "Consultar";
    int tipoS = ((int)Session["userActivoTipo"]);

    if (tipoS == 2)
    {
        Layout = "~/Views/Shared/LayoutLector.cshtml";
    }
    else if (tipoS == 1)
    {
        Layout = "~/Views/Shared/LayoutAdministrador.cshtml";
    }
}

<div class="row">

    <div class="col-md-10" id="consulta">

        <table class="table table-hover" >
            <thead>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Correo</th>
            <th>Dirrecion</th>
            <th>Editar</th>
            <th>Eliminar</th>
            </thead>
            <tbody>
                @{
                    foreach (var editorial in Model)
                    {
                        <tr>
                            <td>@editorial.Nombre</td>
                            <td>@editorial.Telefono</td>
                            <td>@editorial.Correo</td>
                            <td>@editorial.Dirrecion</td>
                            <td><button class="btn btn-info editar" id="@editorial.Id_editorial">Editar</button></td>
                            <td><button class="btn btn-danger eliminar" id="@editorial.Id_editorial">Eliminar</button></td>
                        </tr>
                    }
                }

            </tbody>

        </table>

    </div>

    <div class="col-md-10">
        <button id="btnAgregar" class="btn btn-success">Agregar editorial</button>
    </div>
    <div id="modals">

        <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Modificar editorial</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-8">
                                <label for="Mnombre">Nombre</label>
                                <input id="Mnombre" class="form-control" />
                            </div>
                            <div class="col-md-8">
                                <label for="Mtelefono">Telefono</label>
                                <input id="Mtelefono" class="form-control" />
                            </div>
                            <div class="col-md-8">
                                <label for="Mcorreo">Correo</label>
                                <textarea id="Mcorreo" class="form-control"> </textarea>
                            </div>
                            <div class="col-md-8">
                                <label for="Mdirrecion">Dirrecion</label>
                                <textarea id="Mdirrecion" class="form-control"> </textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <button type="button" class="btn btn-info" id="btnActualizar">Actualizar autor</button>
                    </div>
                </div>
            </div>
        </div>


        <div class="modal fade" id="basicModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar editorial</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-8">
                                <label for="Enombre">Nombre</label>
                                <input id="Enombre" class="form-control" />
                            </div>
                            <div class="col-md-8">
                                <label for="Etelefono">Telefono</label>
                                <input id="Etelefono" class="form-control" />
                            </div>
                            <div class="col-md-8">
                                <label for="Ecorreo">Correo</label>
                                <textarea id="Ecorreo" class="form-control"> </textarea>
                            </div>
                            <div class="col-md-8">
                                <label for="Edirrecion">Dirrecion</label>
                                <textarea id="Edirrecion" class="form-control"> </textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <button type="button" class="btn btn-danger" id="btnEliminar">Eliminar editorial</button>
                    </div>
                </div>
            </div>
        </div>


    </div>

    @section scripts{
        <script>
            $(document).ready(function(){
                console.log(":v");

                $("#btnAgregar").click(function () {
                    document.location = "@Url.Content("~/Editorial/Add")";
                });

                idEditorialM = 0;
                $(document).on('click', '.editar', function (e) {
                    idEditorialM = $(this).attr("id");
                    $("#basicModal").modal("toggle");

                    valor = $(this).parents("tr").find("td");

                    console.log(valor);
                    console.log($("#Mnombre"));
                    $("#Mnombre").val(valor[0].textContent);
                    $("#Mtelefono").val(valor[1].textContent);
                    $("#Mcorreo").val(valor[2].textContent);
                    $("#Mdirrecion").val(valor[3].textContent);
                });


                $("#btnActualizar").click(function () {
                    var ejson = {
                        nEditorial: idEditorialM,
                        nombre: $("#Mnombre").val(),
                        telefono: $("#Mtelefono").val(),
                        correo: $("#Mcorreo").val(),
                        dirrecion: $("#Mdirrecion").val()
                    };
                    $.ajax({
                        url: "@Url.Content("~/Editorial/Edit")",
                        type: "POST",
                        datatype: "json",
                        data: ejson,
                        success: function (data) {
                            if (data==1) {
                                alert("Se ha realizado la modificacion");
                            }

                            document.location = "@Url.Content("~/Editorial/Consult")";
                        }
                    });
                });

                // eliminar
                idEditorial = 0;
                 $(document).on('click', '.eliminar', function (e) {
                     idEditorial = $(this).attr('id');
                     $("#basicModal1").modal("toggle");
                     valor = $(this).parents("tr").find("td");
                     $("#Enombre").val(valor[0].textContent);
                     $("#Etelefono").val(valor[1].textContent);
                     $("#Ecorreo").val(valor[2].textContent);
                     $("#Edirrecion").val(valor[3].textContent);
                });

                $("#btnEliminar").click(function () {
                    var ejson = {
                        nEditorial: idEditorial
                    };
                    $.ajax({
                        url: "@Url.Content("~/Editorial/Delete")",
                        type: "POST",
                        datatype: "json",
                        data: ejson,
                        success: function (data) {
                            if (data==1) {
                                alert("Se ha realizado la eliminacion");
                            }
                            document.location = "@Url.Content("~/Editorial/Consult")";
                        }
                    });
                });
            });
        </script>

    }
</div>

BibliotecaWeb/BibliotecaWeb/Views/Editorial/DaPrueba.cshtml
@model  List < System.Web.Mvc.JsonResult>
    @{
        ViewBag.Title = "DaPrueba";
    }

    <h2>DaPrueba</h2>



@{

    foreach (var item in Model)
    {
    <label>item</label>

        Console.WriteLine(item);
    }

 }