BibliotecaWeb/BibliotecaWeb/Models/ViewModels/AutorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
namespace BibliotecaWeb.Models.ViewModels
{
    public class AutorViewModel
    {
        [Required]
        [Display(Name = "Nombre del autor")]
        [MaxLength(250, ErrorMessage = "El nombre del autor no debe de superar {0} y debe ser mayor a {1} "), MinLength(3)]
        public string Nombre { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha de nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Required]
        [Display(Name ="Descripcion")]
        [MaxLength(250, ErrorMessage = "La descripcion no debe superar a {0}  y debe de ser mayor a {1}"), MinLength(3)]
        public string Descripcion { get; set; }
    }
}

BibliotecaWeb/BibliotecaWeb/Models/autor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public autor()
        {
            this.listaDeseos = new HashSet<listaDeseos>();
            this.libro = new HashSet<libro>();
        }
    
        public int id_autor { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listaDeseos> listaDeseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libro { get; set; }
    }
}

BibliotecaWeb/BibliotecaWeb/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaWeb.Models;
using BibliotecaWeb.Models.ViewModels;
using BibliotecaWeb.Models.TableViewModels;

namespace BibliotecaWeb.Controllers
{
    public class AutorController : Controller
    {


        [HttpGet]
        public ActionResult Autor()
        {

            List<AutorTableViewModel> lista = null;
            using (var db = new bibliotecaEntities1())
            {
                lista = (from t1 in db.autor
                         orderby t1.nombre descending
                         where t1.estado == 1
                         select new AutorTableViewModel
                         {
                             Id_autor = t1.id_autor,
                             Nombre = t1.nombre,
                             Fecha_nacimiento = t1.fecha_nacimiento,
                             Descripcion = t1.descripcion,
                             N_Libros = (from t3 in db.libro where t1.id_autor == t3.fk_autor select t3.id_libro).Count()
                         }).ToList();

                /*    IList<AutorTableViewModel> algo = db.autor.Where(w => w.estado.Equals(1)).OrderByDescending(o => o.nombre)
                                                              .Select(s => new AutorTableViewModel
                                                              {
                                                                  Estado = s.estado ?? 0,  
                                                                  Descripcion = s.descripcion,
                                                                  Fecha_nacimiento = s.fecha_nacimiento,
                                                                  Id_autor = s.id_autor,
                                                                  N_Libros = db.libro.Where(e => e.fk_autor.Equals(s.id_autor)).Count()
                                                              }).ToList();
                */


            }
            return View(lista);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Add(AutorViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }


            using (var bd = new bibliotecaEntities1())
            {
                autor oAutor = new autor
                {
                    nombre = model.Nombre,
                    fecha_nacimiento = model.FechaNacimiento,
                    descripcion = model.Descripcion,
                    estado = 1
                };

                bd.autor.Add(oAutor);
                bd.SaveChanges();
            }

            return Redirect(Url.Content("~/Autor/Autor"));
        }



        public ActionResult Edit(int autor, string nombre, string fechaNacimiento, string descripcion)
        {
            Console.WriteLine(nombre);
            using (var db = new bibliotecaEntities1())
            {
                var oAutor = db.autor.Find(autor);
                oAutor.nombre = nombre;
                oAutor.fecha_nacimiento = Convert.ToDateTime(fechaNacimiento);
                oAutor.descripcion = descripcion;
                db.Entry(oAutor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Content("1");
        }

        public ActionResult Delete(int autor)
        {
            using (var db = new bibliotecaEntities1())
            {
                var oAutor = db.autor.Find(autor);
                oAutor.estado = 2;
                db.Entry(oAutor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Content("1");
        }
    }



}

BibliotecaWeb/BibliotecaWeb/Views/Autor/Add.cshtml
@model BibliotecaWeb.Models.ViewModels.AutorViewModel
@{
    ViewBag.Title = "Agregar autor";
    Layout = "~/Views/Shared/LayoutAdministrador.cshtml";
}
<div class="row">
    <div class="col-md-10">
        @using (Html.BeginForm("Add", "Autor", FormMethod.Post, new { role = "form" }))
        {
            <h3>Agregar Autor</h3>

            <div class="col-md-6">
                @Html.LabelFor(l => l.Nombre)
                @Html.TextBoxFor(l => l.Nombre, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Nombre del autor", new { @class = "text-danger" })
            </div>
            <div class="col-md-6">
                @Html.LabelFor(l => l.FechaNacimiento)
                @Html.TextBoxFor(l => l.FechaNacimiento, new { @class = "text-danger datePicker form-control" })
                @Html.ValidationMessage("Fecha de nacimiento", new { @class = "text-danger"});
            </div>
            <div class="col-md-6">
                @Html.LabelFor(l => l.Descripcion)
                @Html.TextAreaFor(l => l.Descripcion, new { @class = "text-danger form-control" })
                @Html.ValidationMessage("Descripcion", new { @class = "text-danger" })
            </div>
            <div class="col-md-6">
                <button class="btn btn-success">Agregar autor</button>
            </div>

       

        }
    </div>

    @section scripts{
        <script>
            $(document).ready(function () {
                console.log(":v");
                $(".datePicker").datepicker({
                    changeYear: true,
                    changeMonth: true,
                    dateFormat:("yy-mm-dd")
                    
                });
            });
        </script>
    }
</div>

BibliotecaWeb/BibliotecaWeb/Views/Autor/Autor.cshtml
@model List<BibliotecaWeb.Models.TableViewModels.AutorTableViewModel>
@{
    ViewBag.Title = "Autor";

    int tipoS = ((int)Session["userActivoTipo"]);
    if (tipoS == 1){
        Layout = "~/Views/Shared/LayoutAdministrador.cshtml";
    }
}

<div class="row">
    <h2>Autor</h2>
    <div class="col-m-10" id="consulta">
        <table class="table table-hover">
            <thead>
            <th>Autor</th>
            <th>N° Libros</th>
            <th>Fecha de nacimiento</th>
            <th>Descripcion</th>
            <th>Editar</th>
            <th>Eliminar</th>
            </thead>
            <tbody>
                @{
                    foreach (var oAutor in Model)
                    {
                        <tr>
                            <td>@oAutor.Nombre</td>
                            <td>@oAutor.N_Libros</td>
                            <td>@oAutor.Fecha_nacimiento</td>
                            <td>@oAutor.Descripcion</td>
                            <td><button id="@oAutor.Id_autor" class="btn btn-info editar">Editar</button></td>
                            <td><button id="@oAutor.Id_autor" class="btn btn-danger eliminar">Eliminar</button></td>
                        </tr>

                    }
                }
            </tbody>
        </table>

    </div>

    <div class="modal fade" id="basicModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"><strong>Eliminar autor</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-8">
                            <label for="Enombre">Nombre</label>
                            <input id="Enombre" class="form-control" />
                        </div>
                        <div class="col-md-8">
                            <label for="EFechaNacimiento">Fecha de nacimiento</label>
                            <input id="EFechaNacimiento" class="form-control" />
                        </div>
                        <div class="col-md-10">
                            <label for="EDescripcion">Descripcion</label>
                            <textarea id="EDescripcion" class="form-control"> </textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-danger" id="btnEliminar">Eliminar autor</button>
                </div>
            </div>
        </div>
    </div>




    <div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Modificar autor</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-8">
                            <label for="Mnombre">Nombre</label>
                            <input id="Mnombre" class="form-control" />
                        </div>
                        <div class="col-md-8">
                            <label for="MFechaNacimiento">Fecha de nacimiento</label>
                            <input id="MFechaNacimiento" class="form-control" />
                        </div>
                        <div class="col-md-10">
                            <label for="MDescripcion">Descripcion</label>
                            <textarea id="MDescripcion" class="form-control"> </textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-info" id="btnActualizar">Actualizar autor</button>
                </div>
            </div>
        </div>
    </div>



    <div>
        <button id="agregarAutor" class="btn btn-success">Agregar autor</button>
    </div>


    @section scripts{
        <script>
            $(document).ready(function () {
                console.log(":v");
                var autor = 0;
                $(document).on('click', '.editar', function (e) {
                    $("#basicModal").modal("toggle");
                    autor = $(this).attr("id");
                    valores = $(this).parents("tr").find("td");
                    $("#Mnombre").val(valores[0].textContent);
                    $("#MFechaNacimiento").val(valores[2].textContent);
                    $("#MDescripcion").val(valores[3].textContent);
                });


                $("#agregarAutor").click(function () {
                    document.location = '@Url.Content("~/Autor/Add")';
                });

                $("#btnActualizar").click(function () {
                    var json = {
                        autor: autor,
                        nombre:  $("#Mnombre").val(),
                        fechaNacimiento:$("#MFechaNacimiento").val(),
                        descripcion:$("#MDescripcion").val()
                    }
                    $.ajax({
                        url: "@Url.Content("~/Autor/Edit")",
                        datatype: "json",
                        data: json,
                        success: function (data) {
                            console.log("Success");
                            console.log(data);
                            if (data == 1) {
                                alert("Se ha realizado la actualizacion");
                                document.location = '@Url.Content("~/Autor/Autor")';
                            }
                        }
                    });
                });


                var autorE = 0;
                $(document).on('click', '.eliminar', function (e) {
                    autorE = $(this).attr('id');
                    $("#basicModal1").modal("toggle"); 
                    valores = $(this).parents("tr").find("td");
                    $("#Enombre").val(valores[0].textContent);
                    $("#EFechaNacimiento").val(valores[2].textContent);
                    $("#EDescripcion").val(valores[3].textContent);
                });

                $("#btnEliminar").click(function () {
                     var json = {
                         autor: autorE
                    }
                    $.ajax({
                        url: "@Url.Content("~/Autor/Delete")",
                        datatype: "json",
                        data: json,
                        success: function (data) {
                            if (data == "1") {
                                alert("Se ha realizado la eliminacion del autor...");
                            } else {
                                alert("Se produjo un error...");
                            }
                            document.location = "@Url.Content("~/Autor/Autor")";
                        }
                    });
                });

            });
        </script>
    }
</div>